package ifneeded Http 2.1 [list source [file join $dir Http.tcl]]
package ifneeded Cookies 1.0 [list source [file join $dir Cookies.tcl]]
package ifneeded Session 2.0 [list source [file join $dir Session.tcl]]

package ifneeded Debug 2.0 [list source [file join $dir Debug.tcl]]
package ifneeded Timer 1.0 [list source [file join $dir Timer.tcl]]
package ifneeded Pool 1.0 [list source [file join $dir Pool.tcl]]
package ifneeded Threads 1.0 [list source [file join $dir Threads.tcl]]
package ifneeded logging 1.0 [list source [file join $dir logging.tcl]]
package ifneeded Stdin 1.0 [list source [file join $dir Stdin.tcl]]
package ifneeded WubUtils 1.0 [list source [file join $dir WubUtils.tcl]]
package ifneeded Html 1.0 [list source [file join $dir Html.tcl]]
package ifneeded Url 1.0 [list source [file join $dir Url.tcl]]
package ifneeded record 1.0 [list source [file join $dir record.tcl]]
package ifneeded Form 1.0 [list source [file join $dir Form.tcl]]
package ifneeded profiler 1.0 [list source [file join $dir profiler.tcl]]
package ifneeded Query 2.0 [list source [file join $dir Query.tcl]]
package ifneeded Auth 1.0 [list source [file join $dir Auth.tcl]]
package ifneeded Interp 1.0 [list source [file join $dir Interp.tcl]]
package ifneeded Dict 1.0 [list source [file join $dir Dict.tcl]]
package ifneeded View 1.0 [list source [file join $dir View.tcl]]

package ifneeded sgraph 1.0 [list source [file join $dir sgraph.tcl]]
package ifneeded mkdict_tie 1.0 [list source [file join $dir mkdict_tie.tcl]]
package ifneeded utf8 1.0 [list source [file join $dir utf8.tcl]]
package ifneeded passgen 1.0 [list source [file join $dir passgen.tcl]]
package ifneeded captcha 1.0 [list source [file join $dir captcha.tcl]]
package ifneeded spiders 1.0 [list source [file join $dir spiders.tcl]]
