package ifneeded Http 2.1 [list source [file join [list $dir] Http.tcl]]
package ifneeded Cookies 1.0 [list source [file join [list $dir] Cookies.tcl]]

package ifneeded Responder 1.0 [list source [file join [list $dir] Responder.tcl]]

package ifneeded Debug 2.0 [list source [file join [list $dir] Debug.tcl]]
package ifneeded Timer 1.0 [list source [file join [list $dir] Timer.tcl]]
package ifneeded logging 1.0 [list source [file join [list $dir] logging.tcl]]
package ifneeded Stdin 1.0 [list source [file join [list $dir] Stdin.tcl]]
package ifneeded WubUtils 1.0 [list source [file join [list $dir] WubUtils.tcl]]
package ifneeded Html 1.0 [list source [file join [list $dir] Html.tcl]]
package ifneeded Url 1.0 [list source [file join [list $dir] Url.tcl]]
package ifneeded record 1.0 [list source [file join [list $dir] record.tcl]]
package ifneeded Form 2.0 [list source [file join [list $dir] Form.tcl]]
package ifneeded profiler 1.0 [list source [file join [list $dir] profiler.tcl]]
package ifneeded Query 2.0 [list source [file join [list $dir] Query.tcl]]
package ifneeded Auth 1.0 [list source [file join [list $dir] Auth.tcl]]
package ifneeded Dict 1.0 [list source [file join [list $dir] Dict.tcl]]
package ifneeded View 1.0 [list source [file join [list $dir] View.tcl]]
package ifneeded mktie 2.0 [list source [file join [list $dir] mktie.tcl]]
package ifneeded UA 1.0 [list source [file join [list $dir] UA.tcl]]
package ifneeded Report 1.0 [list source [file join [list $dir] Report.tcl]]
package ifneeded Color 1.0 [list source [file join [list $dir] Color.tcl]]

package ifneeded sgraph 1.0 [list source [file join [list $dir] sgraph.tcl]]
package ifneeded mkdict_tie 1.0 [list source [file join [list $dir] mkdict_tie.tcl]]
package ifneeded utf8 1.0 [list source [file join [list $dir] utf8.tcl]]
package ifneeded passgen 1.0 [list source [file join [list $dir] passgen.tcl]]
package ifneeded captcha 1.0 [list source [file join [list $dir] captcha.tcl]]
package ifneeded spiders 1.0 [list source [file join [list $dir] spiders.tcl]]
package ifneeded Sitemap 1.0 [list source [file join [list $dir] Sitemap.tcl]]
package ifneeded Widget 1.0 [list source [file join [list $dir] Widget.tcl]]

package ifneeded scgi 1.0 [list source [file join [list $dir] scgi.tcl]]
